# -*- coding: utf-8 -*-
"""API Verification Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp34h4aRyFma7zyIkdutHK8D14DjAcLa
"""

# verify/test_api.py
import requests, sys, time, json

BASE="http://127.0.0.1:8000"

def health():
    r = requests.get(f"{BASE}/api/health")
    print("=== Health ===")
    print(r.status_code, r.text)

def nodes_map():
    r = requests.get(f"{BASE}/api/nodes/map")
    print("=== Node Map ===")
    print(r.status_code)
    print(json.dumps(r.json(), indent=2))

def request_and_approve(node_code="ENGINE.CORE"):
    # Submit request
    payload = {"node_code": node_code, "evidence": {"note":"test"}}
    r = requests.post(f"{BASE}/api/access/request", json=payload)
    print("Request response:", r.status_code, r.text)
    # List pending
    r = requests.get(f"{BASE}/admin/pending")
    pending = r.json()
    print("Pending:", json.dumps(pending, indent=2))
    if pending:
        access_id = pending[0]["access_id"]
        r = requests.post(f"{BASE}/admin/approve/{access_id}")
        print("Approve response:", r.status_code, r.text)
    else:
        print("No pending found to approve.")

if __name__ == "__main__":
    print("Waiting for server...")
    time.sleep(1)
    health()
    nodes_map()
    request_and_approve()