# -*- coding: utf-8 -*-
"""Database Connection Utility (Mock)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcKJyRsP5SG8D495pzfgTc0wmBAyUjE6
"""

import asyncpg
import os
from typing import Any

# --- Mock Database Configuration ---
# In a real environment, this would connect to a live PostgreSQL server.
# For this blueprint, we use a global variable to simulate the connection pool
# and skip the actual database setup, but maintain the structure required by asyncpg.
_MOCK_DB_POOL: Any = None

async def setup_db_pool():
    """
    Initializes a mock database pool.
    In a live system, this function would use asyncpg.create_pool.
    """
    global _MOCK_DB_POOL
    if _MOCK_DB_POOL is None:
        print("[DB] Initializing MOCK DB Pool (No actual connection established).")
        # In a real app:
        # _MOCK_DB_POOL = await asyncpg.create_pool(
        #     user=os.environ.get("POSTGRES_USER"),
        #     password=os.environ.get("POSTGRES_PASSWORD"),
        #     database=os.environ.get("POSTGRES_DB"),
        #     host=os.environ.get("POSTGRES_HOST")
        # )

        # We simulate the pool object presence for dependencies
        class MockPool:
            async def acquire(self):
                # Simulates acquiring a connection object
                from init_db import MockConnection
                return MockConnection()

        _MOCK_DB_POOL = MockPool()
        print("[DB] MOCK DB Pool ready. Use 'init_db.py' to populate mock data.")
    return _MOCK_DB_POOL

def get_pool():
    """
    Dependency injector for getting the database pool instance.
    """
    global _MOCK_DB_POOL
    if _MOCK_DB_POOL is None:
        raise Exception("Database pool not initialized. Call setup_db_pool() first.")
    return _MOCK_DB_POOL

async def shutdown_db_pool():
    """
    Closes the mock database pool.
    """
    global _MOCK_DB_POOL
    if _MOCK_DB_POOL:
        # In a real app: await _MOCK_DB_POOL.close()
        print("[DB] MOCK DB Pool shutdown complete.")
        _MOCK_DB_POOL = None