# -*- coding: utf-8 -*-
"""FastAPI Main Application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whvtvhRJFZhKz0nl3jK2tYHpu97hoIRF
"""

# app/main.py
import asyncio
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
from app.db import setup_db_pool, shutdown_db_pool
from app.ws import manager
from app.admin import router as admin_router
from app.routes import router as api_router
from app.logger import logger

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("--- [STARTUP] Sovereign system starting ---")
    await setup_db_pool()
    logger.info("--- [LIFESPAN] Sovereign DB ready ---")
    yield
    logger.info("--- [SHUTDOWN] Closing DB ---")
    await shutdown_db_pool()

app = FastAPI(title="Trideva Access Engine API", version="1.0.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router)
app.include_router(admin_router)

@app.websocket("/ws/updates")
async def ws_updates(ws: WebSocket, token: str = None):
    # token is optional; in production validate token to determine user_id / admin
    user_id = None
    is_admin = False
    # simple mapping for dev: if ?token=ADMIN then admin
    if token == "ADMIN":
        is_admin = True
        user_id = "ADMIN.AARON"
    elif token:
        user_id = token
    await manager.connect(ws, user_id=user_id, is_admin=is_admin)
    try:
        while True:
            await ws.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(ws)
    except Exception:
        manager.disconnect(ws)