# -*- coding: utf-8 -*-
"""Python Package Marker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljIuXDmQER_BikYup66Ry9g3lMopz5pG
"""

# app/__init__.py
# package marker