# -*- coding: utf-8 -*-
"""Simple Logger Utility

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6zoUAv81039Oqk-3MV5w1nIV6GBONIv
"""

# app/logger.py
import logging, sys

def get_logger(name="trideva"):
    logger = logging.getLogger(name)
    if not logger.handlers:
        handler = logging.StreamHandler(sys.stdout)
        fmt = logging.Formatter("[%(asctime)s] %(levelname)s %(name)s: %(message)s")
        handler.setFormatter(fmt)
        logger.addHandler(handler)
        logger.setLevel(logging.INFO)
    return logger

logger = get_logger()